name: First Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Salem DevOps!"
      - name: Print goodbye
        run: echo "Sau Bol DevOps!"
      
